### ISSUE TITLE
About network performance

### ISSUE THREAD

**Issue by emjay73** [seominjoon/kaist-ai605#72]
I'm struggling to meet the reasonable performance of the text classifier with a self-implemented network. (Both FC and RNN)
If I've done things right, I'm having an accuracy of ~50%, which is almost the same as the random guess.
I set the hidden state dimension as 128.
Are there any other things that I can try to increase the accuracy?

**Comment by seominjoon** [comment]
Hi, please use Q&As for questions. I am closing this issue.
